### ISSUE TITLE
Thieves Guild no longer shows on map for members

### ISSUE THREAD

**Issue by Interkarma** [Interkarma/daggerfall-unity#1381]
**Describe the bug**
Thieves Guild (and assuming Dark Brotherhood) no longer appear on map when character is a member.

Link to topic on forums.
https://forums.dfworkshop.net/viewtopic.php?f=5&t=2386

Possibly another regression from https://github.com/Interkarma/daggerfall-unity/commit/2b219142ec822904d0c94736c96a49f6a1e0095c as with lockpicking state.

@Nystul-the-Magician Is this something you would like any help with? Please just let me know and I will do what I can to assist. It might be best to just revert that change for now and then tackle from a different angle.

**Comment by ajrb** [comment]
This could be simply because when I implemented the guilds and this function, I integrated with how the discovery code worked back then. Possibly the guild functions just need adjusting, but I think Nystul will need to judge that. Happy to rework them if needed and someone can explain what changed conceptually.

**Comment by Nystul-the-Magician** [comment]
happy to take a look, but will not have time before start of next week :)

**Comment by ajrb** [comment]
I've taken a look and this change 2b21914 has broken the returning of discovery data and now calls GetBuildingDiscoveryData() which seems to build it from the location building directory and completely ignores the overridden names in the discovery data. Since this is where the guilds set the display name override, that's why the guild nameing has broken.

The code removed has not been replaced just by calling GetBuildingDiscoveryData() and I cannot work out why this is being called now. When a building is discovered in a location and added to the dict it has all the data in a DiscoveredBuilding data structure, including name overrides for quests and guilds etc. Why regenerate all that every time, if that's the way forward then the DiscoveredBuilding struct is pretty pointless or that's my reading of it at least.

The player house handling was done slightly differently and you preserved that since the code was explicitly there, but anything that overrides the discovered building name will have broken with this change I am afraid.

It may be because I don't really understand how this fix was intended to correct the bug reported, but I think it should be reverted and the original bug and approach to fixing it analysed again.

**Comment by Nystul-the-Magician** [comment]
> It may be because I don't really understand how this fix was intended to correct the bug reported, but I think it should be reverted and the original bug & approach to fixing it analysed again. I think the temp discovery data cached, and the ability to override names using it, needs to remain. However, if someone has a better idea for how to handle name overriding then I am all ears.
it should be an easy fix, pls just don't revert - I think it is a one line change to solve this and it should be clearer then - before it was really happening in different functions and I just wanted to merge all into one - I just think I overseen something trivial

**Comment by Nystul-the-Magician** [comment]
if I try to just undo the changes done by 2b21914 on current code I still don't get the Thieves guild to show up - ajrb, are you really sure it is from this change?

still testing...

**Comment by Nystul-the-Magician** [comment]
ajrb, please take a look at the pull request - I think this solves now the issue:
if there is an override name this building name is taken otherwise further building name resolving is done.
I also streamlined the public function (GetDiscoveredBuilding) to only call the private one (GetBuildingDiscoveryData) which does all the name resolving.
We could consider moving the code from the private one to the public and replacing the calls to the private with the public one - since it now does nothing else
btw: differences in these 2 functions before changes in 2b21914 were made caused this issue: https://forums.dfworkshop.net/viewtopic.php?f=28&t=2227

**Comment by ajrb** [comment]
> edit: I would like to iterate on the building discovery implementation a bit next week - to make it easier to understand and less obfuscated

Well that i would welcome for sure. Happy to hold off if you intend to sort the messiness out, and  then I will hopefully see what's happening. Also happy if you want to do an alternative mechanism for doing the guild names etc, I'm not attached to it at all.

What i do know is I do not want to sort the discovery code out 'cos I have only limited understanding. :-) Happy to re-implement the guild code using it if needed though.

And no need to rush from my PoV, take your time and do it right.

**Comment by Interkarma** [comment]
Another possibility related regression issue from change to discovery.

https://forums.dfworkshop.net/viewtopic.php?f=25&t=2411&p=28156#p28156

Logging here so I can check later and don't forget.

**Comment by Nystul-the-Magician** [comment]
closed the old pr and created a new one with my (slight) rework of the system: https://github.com/Interkarma/daggerfall-unity/pull/1391

**Comment by Interkarma** [comment]
I'm happy with fix in #1391 and will merge this tomorrrow unless someone objects. Thanks for your work on this Nystul!

Closing issue now.
